### ISSUE TITLE
Not downloading all clips

### ISSUE THREAD

**Issue by cowboy-1337** [Dave-Swagten/Medal.tv-Bulk-Downloader#7]
I have 507 clips and it only downloads 239

**Comment by Dave-Swagten** [comment]
Hello!

It sounds like this issue might be related to Medal's public and private clip logic. Could you confirm if you've followed the setup instructions carefully, especially the steps under the "Set up your username and Cookies" section in the README? Here’s a quick link for reference: [README Setup Guide](https://github.com/Dave-Swagten/Medal.tv-Bulk-Downloader?tab=readme-ov-file#2-set-up-your-username-and-cookies)

**Comment by cowboy-1337** [comment]
yes, i put in my username, web cookies, and the X-Authentication cookie

**Comment by Dave-Swagten** [comment]
Could you double-check that you're logged into the correct account where the cookies were exported from and that the configuration file is set up correctly? If everything is configured according to the instructions, it should work as expected. If it's still not working, I can take a look at it tonight (CET).

**Comment by Dave-Swagten** [comment]
Hello there, apologies for the late response.

I found the issue: Medal has decreased their API limit for fetching content from 100 to 60. This results in a 40% reduction in clips being fetched per request, but the script currently increments the offset by 100, causing it to skip 40 clips with each batch. Based on your numbers, this is most likely the cause.

I'm currently working on a website to download Medal clips, and it's shaping up to be a great tool! The website is incredibly fast and provides a clear, user-friendly interface with an organized overview of your Medal clips. Once the website is released, I’ll also update this script to ensure it works seamlessly.

**Comment by cowboy-1337** [comment]
Alright, awesome

**Comment by Dave-Swagten** [comment]
I’m excited to announce the release of a new tool to make downloading your Medal clips even easier: [BulkDL](https://bulkdl.net/)!

The website is lightning-fast, with a clean and intuitive interface that gives you a clear overview of all your Medal clips. You can quickly browse, select, and download your clips with ease.  

Feel free to check it out and let me know if you have any feedback! I'll also update the Medal Bulk Downloader script soon to align with the latest changes.  

Enjoy using the tool! 🎉
